### ISSUE TITLE
class "js-global-new-tweet" not found.

### ISSUE THREAD

**Issue by aspiringguru** [pranavraikote/Python-Selenium-Tweeting#1]
ffound this in Feb 2021. No doubt twitter have changed their design and scaled up their efforts to obstruct automation tools.

When I dug through the dom I found all kinds of weird class names, obtuse dom structures etc. So not surprised this old method didn't work.

thanks for the original work though. I have been using python tweepy package, tho twitter limits on anything other than data collection means any twitter automation is _very_ limited. (which is actually expected, it was a wild wild west for a long time)

**Comment by pranavraikote** [comment]
Yeah. It's pretty old and we do have twitter's official API to get tweet data (Although it's limited in terms of no. of tweets collected). You can use selenium and try to create a workaround, use tweepy or head to kaggle/dataset repositories for large tweet data.

Thanks for appreciating one of my older repository!
